import{a as q,S,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function m(r,o){const{data:i}=await q("https://pixabay.com/api/",{params:{key:"50837011-c76ef50eb9608d9d0e02a1779",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:o}});return i}const E=new S(".gallery a"),h=document.querySelector(".loader"),f=document.querySelector(".load-more"),y=document.querySelector(".gallery");function p(r){const o=r.map(({webformatURL:i,largeImageURL:l,tags:e,likes:t,views:a,comments:v,downloads:w})=>`
   <li class="gallery-item">
        <a href="${l}">
          <img src="${i}" alt="${e}" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${a}</p>
          <p><b>Comments:</b> ${v}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",o),E.refresh()}function $(){y.innerHTML=""}function g(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function L(){f.classList.remove("load-more-hidden")}function c(){f.classList.add("load-more-hidden")}const M=document.querySelector(".form");M.addEventListener("submit",O);f.addEventListener("click",P);let s=1,d=0,u="";async function O(r){r.preventDefault();const o=r.target.elements.searchText.value.trim();if(!o){n.error({title:"Error",message:"Please enter a search query!"});return}u=o,s=1,$(),c(),g();try{const i=await m(u,s);if(d=i.totalHits,i.hits.length===0){n.info({title:"No Results",message:"No images found."});return}p(i.hits),d>s*15&&L()}catch{n.error({title:"Error",message:"Failed to fetch images."})}finally{b()}}async function P(){s++,c(),g();try{const r=await m(u,s);p(r.hits),s*15>=d?(n.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results."}),c()):L(),x()}catch{n.error({title:"Error",message:"Failed to load more images."})}finally{b()}}function x(){const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
